# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS (Matt Middleton)">
# Copyright (c) Meridian Technology Consulting Services (Matt Middleton).
# All rights reserved.
# </copyright>
# -----------------------------------------------------------------------------

# Configuration
configuration: release

# Before Build Config
before_build:
  - nuget restore Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.sln

# Build Config
build:
  project: Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.sln

# After Build Config
after_build:
- cmd: |
    xcopy /s %APPVEYOR_BUILD_FOLDER%\Licences %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\bin\Release\
    copy %APPVEYOR_BUILD_FOLDER%\LICENCE.md %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\bin\Release\aws-pwe-LICENCE.txt
    copy %APPVEYOR_BUILD_FOLDER%\VERIFICATION.txt %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\bin\Release\VERIFICATION.txt
    copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\bin\Release\ReadMe.txt
    7z a aws-pe.zip %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\bin\Release\*.*
    AppVeyor PushArtifact aws-pe.zip -DeploymentName "aws-pe Binaries"
    choco pack %APPVEYOR_BUILD_FOLDER%\Meridian.AwsPasswordExtractor\Meridian.AwsPasswordExtractor.Console\Meridian.AwsPasswordExtractor.Console.nuspec

# Artifact Config
artifacts:
  - path: "*.nupkg"
    name: aws-pe Chocolatey Pacakge